name: Publish Release
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  lint:
    name: ESLint
    uses: ./.github/workflows/lint.yml
  publish:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Publish
        run: pnpm publish --provenance --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
